name: Copilot Setup Steps

# This file configures the development environment for GitHub Copilot

env:
  COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: deno.land,lib.deno.dev,jsr.io

steps:
  # Setup Deno
  - uses: denoland/setup-deno@v2
    with:
      deno-version: v2.x

  # Setup Docker Buildx
  - name: Setup Docker Buildx
    uses: docker/setup-buildx-action@v3